In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
d1= pd.read_csv('C:/Users/user/Desktop/mushrooms.csv')  


In [3]:
d1

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [4]:
d1.shape

(8124, 23)

# Checking the basic details.

In [5]:
d1.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
d1.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

###### no null values in the set

In [7]:
d1.nunique() # NO of unique values in each column

class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

# Preprocessing of data.

In [8]:
X=d1.iloc[:,1:19]
y=pd.DataFrame(d1["class"])

In [9]:
X=pd.get_dummies(X)

In [10]:
X

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               1            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
8119            0            0            0            1            0   
8120            0            0            0            0            0   
8121            0            0            1            0            0   
8122            0            0            0            1            0   
8123            0            0            0            0            0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0               1              0              0              1              0   
1               1              0              0              1              0   
2               0              0              0              1              0   
3               1              0              0              0              1   
4               1              0              0              1              0   
...           ...            ...            ...            ...            ...   
8119            0              0              0              1              0   
8120            1              0              0              1              0   
8121            0              0              0              1              0   
8122            0              0              0              0              1   
8123            1              0              0              1              0   

      ...  stalk-color-below-ring_w  stalk-color-below-ring_y  veil-type_p  \
0     ...                         1                         0            1   
1     ...                         1                         0            1   
2     ...                         1                         0            1   
3     ...                         1                         0            1   
4     ...                         1                         0            1   
...   ...                       ...                       ...          ...   
8119  ...                         0                         0            1   
8120  ...                         0                         0            1   
8121  ...                         0                         0            1   
8122  ...                         1                         0            1   
8123  ...                         0                         0            1   

      veil-color_n  veil-color_o  veil-color_w  veil-color_y  ring-number_n  \
0                0             0             1             0              0   
1                0             0             1             0              0   
2                0             0             1             0              0   
3                0             0             1             0              0   
4                0             0             1             0              0   
...            ...           ...           ...           ...            ...   
8119             0             1             0             0              0   
8120             1             0             0             0              0   
8121             0             1             0             0              0   
8122             0             0             1             0              0   
8123             0             1             0             0              0   

      ring-number_o  ring-number_t  
0                 1              0  
1                 1              0  
2                 1              0  
3                 1              0  
4                 1              0  
...             ...            ...  
8119       

# Splitting the data set to training set and testing set.

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test= train_test_split(X,y,random_state=0,test_size=.25)

In [12]:
d1.nunique()

class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

# Logical Regression.

In [13]:
from sklearn.linear_model import LogisticRegression # import logical regression from skl library and create the model
logit_model = LogisticRegression()          # to create an instance of the model
logit_model.fit(X_train, y_train) # to fit the regression model
y_prediction= logit_model.predict(X_test) # to predict y value

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [15]:
print("Accuracy is ",accuracy_score(y_test, y_prediction))

Accuracy is  0.999015263417036


In [16]:
print("\n Confusion matrix")
confusion_matrix(y_test, y_prediction)


 Confusion matrix


array([[1060,    1],
       [   1,  969]], dtype=int64)

# Fitting Gaussian Naive Bayes To training data

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [18]:
y_pred= classifier.predict(X_test) # To predicit the value

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy is ",accuracy_score(y_test, y_pred))
print("\n Confusion matrix")
confusion_matrix(y_test, y_pred)

Accuracy is  0.9921221073362876

 Confusion matrix


array([[1061,    0],
       [  16,  954]], dtype=int64)

# Fitting Bernoulli Naive Bayes To training data.

In [20]:
from sklearn.naive_bayes import BernoulliNB
classifier= BernoulliNB()
classifier.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


BernoulliNB()

In [21]:
y_pred= classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy is ",accuracy_score(y_test, y_pred))
print("\n Confusion matrix")
confusion_matrix(y_test, y_pred)

Accuracy is  0.983259478089611

 Confusion matrix


array([[1060,    1],
       [  33,  937]], dtype=int64)